# Generated by Django 4.0.7 on 2022-12-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_notifications_timestamp_alter_notifications_isread_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='timestamp',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='userid',
            field=models.PositiveIntegerField(),
        ),
    ]
