# Generated by Django 4.0.7 on 2022-12-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_timestamp_notifications_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='link',
            field=models.TextField(default='null'),
        ),
    ]
