# Generated by Django 4.0.4 on 2022-05-14 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='article',
            new_name='quiz',
        ),
    ]
