# Generated by Django 4.0.3 on 2022-03-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=250)),
                ('wikidata_item_identifier', models.CharField(max_length=50)),
            ],
        ),
    ]
