# Generated by Django 4.0.3 on 2022-03-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_cover_image_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_image_uri',
            field=models.CharField(max_length=1024, null=True, verbose_name='Cover Image URI'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='game',
            name='wikidata_item_identifier',
            field=models.CharField(max_length=50, verbose_name='Wikidata Item Identifier'),
        ),
    ]
