# Generated by Django 4.0.4 on 2022-05-11 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0002_space_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='subscribed_users',
            field=models.ManyToManyField(related_name='space_subscribed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
