# Generated by Django 4.0.4 on 2022-05-11 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='space',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='spaces.space'),
            preserve_default=False,
        ),
    ]
