# Generated by Django 4.0.4 on 2022-05-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_article_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
