# Generated by Django 4.0.4 on 2022-05-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_alter_article_updated_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
