# Generated by Django 4.0.4 on 2022-05-19 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=65535)),
                ('space', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='space_main_page', to='spaces.space')),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='main_page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='space_main_page', to='spaces.mainpage'),
        ),
    ]
