# Generated by Django 4.0.7 on 2023-01-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0008_mainpage_space_main_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=65535)),
                ('descripion', models.TextField(max_length=65535)),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='related_spaces',
            field=models.ManyToManyField(null=True, related_name='space_related_spaces', to='spaces.space'),
        ),
        migrations.AddField(
            model_name='space',
            name='semantic_tags',
            field=models.CharField(max_length=65535, null=True),
        ),
    ]
