# Generated by Django 4.0.3 on 2022-04-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colearnappuser',
            name='interests',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
